modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="sac"
version="1.0.0"
displayName="Scrili AntiCheat"
description="Server & Client AntiCheat for Minecraft 1.20.1"

[[dependencies.sac]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sac]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
